# Set all versions
#PEARL_BUILD_TYPE ?= UNOFFICIAL

PEARL_DATE_YEAR := $(shell date -u +%Y)
PEARL_DATE_MONTH := $(shell date -u +%m)
PEARL_DATE_DAY := $(shell date -u +%d)
PEARL_DATE_HOUR := $(shell date -u +%H)
PEARL_DATE_MINUTE := $(shell date -u +%M)
PEARL_BUILD_DATE_UTC := $(shell date -d '$(PEARL_DATE_YEAR)-$(PEARL_DATE_MONTH)-$(PEARL_DATE_DAY) $(PEARL_DATE_HOUR):$(PEARL_DATE_MINUTE) UTC' +%s)
PEARL_BUILD_DATE := $(PEARL_DATE_YEAR)$(PEARL_DATE_MONTH)$(PEARL_DATE_DAY)-$(PEARL_DATE_HOUR)$(PEARL_DATE_MINUTE)

PEARL_PLATFORM_VERSION := 9.0

TARGET_PRODUCT_SHORT := $(subst aosp_,,$(PEARL_BUILD))

PEARL_VERSION := PearlOS_$(PEARL_BUILD)-$(PEARL_PLATFORM_VERSION)-$(PEARL_BUILD_DATE)-$(PEARL_BUILD_TYPE)
PEARL_VERSION_PROP := Pie
ROM_FINGERPRINT := PearlOS/$(PEARL_PLATFORM_VERSION)/$(TARGET_PRODUCT_SHORT)/$(PEARL_BUILD_DATE)

PEARL_PROPERTIES := \
    org.pearl.version=$(PEARL_VERSION_PROP) \
    org.pearl.build_date=$(PEARL_BUILD_DATE) \
    org.pearl.build_date_utc=$(PEARL_BUILD_DATE_UTC) \
    org.pearl.build_type=$(PEARL_BUILD_TYPE) \
    org.pearl.fingerprint=$(ROM_FINGERPRINT)
